### ISSUE TITLE
Can plugin download just the nativeImage binary

### ISSUE THREAD

**Issue by yschimke** [palantir/gradle-graal#115]
Download links for 19.0.0 and 19.0.2 have e.g.

https://github.com/oracle/graal/releases/download/vm-19.0.2/native-image-installable-svm-darwin-amd64-19.0.2.jar

10mb vs 300mb

**Comment by nhoughto** [comment]
I wonder how that effects options such as `--language:js` where the GraalJS project (bundled with GraalVM proper) is used, plus TRegex etc that are bundled. 10mb jar isn't going to cut it for everything. Maybe an option to use just native-image vs full graalvm?

**Comment by markelliot** [comment]
Sorry for the delay, we've addressed this in 0.4.0.
