### ISSUE TITLE
Allow for native-image arguments in configuration

### ISSUE THREAD

**Issue by wieki** [palantir/gradle-graal#15]
For some libraries it's necessary to enable the -H:+JNI flag, to be able to build a proper native image. Currently the Gradle nativeImage task doesn't allow for setting this execution parameter. 

Allowing for other configuration like configuration files, could also help (e.g. to set resolve possible reflection issues with a reflect.json)

**Comment by markelliot** [comment]
Definitely a fair flag -- I'm thinking we should add an `arguments` key that enables you to add additional arguments (possibly on a whitelist) to the nativeImage task.

Possibly something we can get to in a couple of weeks, but if you're interested, I'd love to iterate on a design/implementation with you.

**Comment by machaval** [comment]
I think this issue can be closed as for https://github.com/palantir/gradle-graal/pull/22

**Comment by uschi2000** [comment]
Thanks again, @machaval
