### ISSUE TITLE
Please Release 4.0.1

### ISSUE THREAD

**Issue by machaval** [palantir/gradle-graal#184]
Can you guys please release 4.0.1 so that windows support is enabled. Thanks

**Comment by koppor** [comment]
Refs https://github.com/palantir/gradle-graal/pull/127 (where the Windows build was enabled)

**Comment by carterkozak** [comment]
Sorry for the delay, I'm planning to cut a release when I fix publications.

**Comment by carterkozak** [comment]
Happy hacking! https://github.com/palantir/gradle-graal/releases/tag/0.5.0
