### ISSUE TITLE
Wrong url on osx for 19.x

### ISSUE THREAD

**Issue by ekmett** [palantir/gradle-graal#219]
## What happened?

Using
```
plugins { 
 id("com.palantir.graal") version "0.3.0-6-g0b828af"
}
graal {
  graalVersion("19.2.0.1")
}
```
on osx tries to fetch

https://github.com/oracle/graal/releases/download//vm-19.2.0.1/graalvm-ce-19.2.0.1-macos-amd64.tar.gz

which does not exist instead of

https://github.com/oracle/graal/releases/download/vm-19.2.0.1/graalvm-ce-darwin-amd64-19.2.0.1.tar.gz

which does.

## What did you want to happen?

I'd like it to find the file.

**Comment by carterkozak** [comment]
Have you tried the latest release, 0.6.0?

**Comment by ekmett** [comment]
Derp. I was following some dated guide I found online.
