### ISSUE TITLE
Graal 20.0.0 in Windows - gu not found because extension is .cmd instead of .exe

### ISSUE THREAD

**Issue by pexi** [palantir/gradle-graal#344]
## What happened?

Running the nativeImage task fails in windows because the ExtractGraalTask.java cannot find graal updater binary. It is looking for gu.exe but in the graal distribution it is .cmd.

Using version 0.7.0 of the gradle plugin and javaVersion set to 11.

## What did you want to happen?

ExtractGraalTask should look for gu.cmd instead of gu.exe

gu should be added to WINDOWS_CMD_BINARIES in ExtractGraalTask.java

**Comment by UkonnRa** [comment]
+1
