### ISSUE TITLE
Incompatible with Gradle 4.x?

### ISSUE THREAD

**Issue by russelldavis** [palantir/gradle-graal#47]
I tried adding it to my project that uses gradle 4.8, and got the following error:

```
An exception occurred applying plugin request [id: 'com.palantir.graal', version: '0.2.0-17-g543ec9e']
> Failed to apply plugin [id 'com.palantir.graal']
   > Could not create an instance of type com.palantir.gradle.graal.GraalExtension_Decorated.
      > org.gradle.api.provider.ListProperty.empty()Lorg/gradle/api/provider/ListProperty;
```

Upgrading to the latest version of gradle (5.1) fixed it. I'm guessing this is just an incompatibility with older versions of Gradle? If so, should this be documented in the README?

**Comment by markelliot** [comment]
Yeah, we should document the min-Gradle version in the README.

**Comment by koppor** [comment]
I updated to Gradle 5.x in https://github.com/adoble/adr-j/pull/16.

**Comment by Iltotore** [comment]
The minimal version tu run this plugin is 5.0. You should upgrade now. 4.8 is old.
