### ISSUE TITLE
Choose architecture / Build for all architectures

### ISSUE THREAD

**Issue by nhoughto** [palantir/gradle-graal#62]
At the moment it seems like the `nativeImage` task just builds for the current architecture (macos, linux etc). It would be nice to be able to specify or be able to build a macos binary from a linux ci build agent and i guess windows too when they release support for it..

**Comment by markelliot** [comment]
Definitely agree -- but need Graal to support that first :) https://github.com/oracle/graal/issues/407

**Comment by nhoughto** [comment]
Ah didn’t realize cross compile wasn’t a thing! 😬 thanks for the plugin either way 👍🏼
