### ISSUE TITLE
Allow `-H:Name=` or switch argument ordering

### ISSUE THREAD

**Issue by nhoughto** [palantir/gradle-graal#63]
There is a bug with `native-image` at least in `1.0.0-rc12` that the order of `-H:Name` and `-language` effects the outputted binary name: https://github.com/oracle/graal/issues/1032

Since the plugin forces `option` arguments to be placed after the arguments generated by `outputName` when calling `native-image` and forbids manually setting `-H:Name`, i am currently stuck with a binary named `js` because i'm using `-language:js` as an option 😢

**Comment by markelliot** [comment]
This was resolved in #65.
